### ISSUE TITLE
ошибка подсчета статистик на коротких текстах

### ISSUE THREAD

**Issue by xeonvs** [SergeyShk/ruTS#5]
Простой пример:
```
ds = DiversityStats('саид, ты опять абдулле насолил?').get_stats()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ruts/diversity_stats.py", line 163, in get_stats
    'dttr': self.dttr,
  File "/usr/local/lib/python3.6/dist-packages/ruts/diversity_stats.py", line 119, in dttr
    return calc_dttr(self.words)
  File "/usr/local/lib/python3.6/dist-packages/ruts/diversity_stats.py", line 300, in calc_dttr
    return log10(n_words)**2 / (log10(n_words) - log10(n_lexemes))
ZeroDivisionError: float division by zero
```
Проверялось на 0.5.0

**Comment by LSinev** [comment]
Не могли бы вы зарелизить с этим исправлением поскорее, а то пользоваться хочется, а устанавливать из git возможности нет?

**Comment by LSinev** [comment]
Тем более, что в репозиторий месяц уже коммитов не было, а это прям баг — можно 0.5.1 выпустить ;)

**Comment by SergeyShk** [comment]
> Тем более, что в репозиторий месяц уже коммитов не было, а это прям баг — можно 0.5.1 выпустить ;)

Пока залил на тестовый сервер, просьба проверить:

pip install -i https://test.pypi.org/simple/ ruts==0.5.1

**Comment by LSinev** [comment]
вроде бы, нормально работает

**Comment by SergeyShk** [comment]
Ок. Залил на основной сервер.

**Comment by puffofsmoke** [comment]
ruts==0.5.1

```from ruts import DiversityStats
  text = 'яблоко'
  rs = DiversityStats(text)
  rs.get_stats()```

```
Traceback (most recent call last):
  File "[some_path]\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-4460029d1d6f>", line 4, in <module>
    rs.get_stats()
  File "[some_path]\lib\site-packages\ruts\diversity_stats.py", line 162, in get_stats
    'sttr': self.sttr,
  File "[some_path]\lib\site-packages\ruts\diversity_stats.py", line 112, in sttr
    return calc_sttr(self.words)
  File "[some_path]\lib\site-packages\ruts\diversity_stats.py", line 266, in calc_sttr
    return safe_divide(log10(log10(n_lexemes)), log10(log10(n_words)))
ValueError: math domain error
```

**Comment by SergeyShk** [comment]
Спасибо, исправлю.
